import { Roboto } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "@/components/utils/context";
import { AuthProvider } from "@/components/utils/authProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });
// const punycode = require("punycode");

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// process.emitWarning = () => {};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ContextProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ContextProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
